server:
  port: 9090

info:
  component: Zuul Server

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    auth:
      path: /phonebook/uaa/api/**
      serviceId: auth
      stripPrefix: false
    profile:
      path: /phonebook/profile-service/api/**
      serviceId: profile
      stripPrefix: false # needed because of setting context path
    news:
      path: /phonebook/news-service/api/**
      serviceId: news
      stripPrefix: false

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:10000/phonebook/uaa/api/users/current
  user:
    password: none

---
spring:
  profiles: container
server:
  port: ${GATEWAY_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka
security:
  oauth2:
    resource:
      user-info-uri: http://auth:${AUTH_PORT}/phonebook/uaa/api/users/current
