spring:
  application:
    name: gateway
zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    profile-service:
      path: /phonebook/v1/api/profiles/**
      serviceId: profile-service
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 4000