spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phonebook
    username: root
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level: debug
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 10000
  context-path: /phonebook/uaa/api

---
spring:
  profiles: container
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
eureka:
    client:
      service-url:
        defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka
server:
  port: ${AUTH_PORT}